import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";

import { resolveSsrCacheHeaders } from "@agent-native/core/server/ssr-handler";
import { afterEach, describe, expect, it, vi } from "vitest";

import {
  renderNetlifyHeaders,
  writeNetlifyHeaders,
} from "../lib/netlify-headers";
import {
  applyCommunityAppSsrCacheHeaders,
  applyDocsSsrCacheKeyHeaders,
} from "../lib/ssr-cache";

const docsNetlifyConfig = readFileSync(
  new URL("../netlify.toml", import.meta.url),
  "utf8",
);

describe("Docs SSR cache key wrapper", () => {
  afterEach(() => {
    vi.unstubAllEnvs();
  });

  it("preserves core's full-query key for query-sensitive redirects", () => {
    const headers = new Headers({ "netlify-vary": "query" });

    applyDocsSsrCacheKeyHeaders(headers);

    expect(headers.get("netlify-vary")).toBe("query");
  });

  it("applies the normal narrowed key to ordinary public SSR responses", () => {
    vi.stubEnv("NETLIFY", "true");
    const headers = new Headers();

    applyDocsSsrCacheKeyHeaders(headers);

    expect(headers.get("netlify-vary")).toBe("query=_routes|index");
  });

  it("shortens only mutable community app routes", () => {
    const communityHeaders = new Headers();
    applyCommunityAppSsrCacheHeaders(communityHeaders, "/es-es/apps/");
    expect(communityHeaders.get("cache-control")).toContain("max-age=30");

    const staticHeaders = new Headers();
    applyCommunityAppSsrCacheHeaders(staticHeaders, "/docs/getting-started/");
    expect(staticHeaders.get("cache-control")).toBeNull();
  });

  it("keeps prerendered public pages on core's default SWR cache policy", () => {
    const coreHeaders = resolveSsrCacheHeaders({});
    const netlifyHeaders = renderNetlifyHeaders({});

    expect(netlifyHeaders).toContain(
      `Cache-Control: ${coreHeaders["cache-control"]}`,
    );
    expect(netlifyHeaders).toContain(
      `CDN-Cache-Control: ${coreHeaders["cdn-cache-control"]}`,
    );
    expect(netlifyHeaders).toContain(
      `Netlify-CDN-Cache-Control: ${coreHeaders["netlify-cdn-cache-control"]}`,
    );
    expect(netlifyHeaders).toContain("stale-while-revalidate");
    expect(netlifyHeaders).not.toContain("max-age=0");
    expect(netlifyHeaders).not.toContain("must-revalidate");
  });

  it("generates static cache headers from the shared Netlify build", () => {
    expect(docsNetlifyConfig).toContain(
      "NITRO_PRESET=netlify pnpm --filter @agent-native/docs build",
    );
    expect(docsNetlifyConfig).not.toContain("generate-netlify-headers");
    expect(docsNetlifyConfig).toContain('publish = "packages/docs/dist"');
  });

  it("applies the deployment-wide SSR cache override to static pages", () => {
    const netlifyHeaders = renderNetlifyHeaders({
      AGENT_NATIVE_SSR_CACHE: "5m",
    });

    expect(netlifyHeaders).toContain(
      "Cache-Control: public, max-age=300, stale-while-revalidate=300, stale-if-error=3600",
    );
    expect(netlifyHeaders).toContain(
      "Netlify-CDN-Cache-Control: public, durable, s-maxage=300, stale-while-revalidate=300, stale-if-error=3600",
    );
    expect(netlifyHeaders).toContain(
      "/assets/*\n  Cache-Control: public, max-age=31536000, immutable",
    );
  });

  it("applies the deployment-wide no-store override to static pages", () => {
    const netlifyHeaders = renderNetlifyHeaders({
      AGENT_NATIVE_SSR_CACHE: "off",
    });

    expect(netlifyHeaders).toContain("/*\n  Cache-Control: no-store");
    expect(netlifyHeaders).toContain("  CDN-Cache-Control: no-store");
    expect(netlifyHeaders).toContain("  Netlify-CDN-Cache-Control: no-store");
    expect(netlifyHeaders).toContain(
      "/assets/*\n  Cache-Control: public, max-age=31536000, immutable",
    );
  });

  it("preserves existing Netlify headers when regenerating the policy", () => {
    const publishDir = mkdtempSync(
      path.join(os.tmpdir(), "agent-native-docs-headers-"),
    );

    try {
      const headersPath = path.join(publishDir, "_headers");
      writeFileSync(headersPath, '/*\n  Link: </llms.txt>; rel="llms-txt"\n');
      writeNetlifyHeaders(publishDir, {});
      writeNetlifyHeaders(publishDir, {
        AGENT_NATIVE_SSR_CACHE: "5m",
      });

      const headers = readFileSync(headersPath, "utf8");
      expect(headers).toContain('Link: </llms.txt>; rel="llms-txt"');
      expect(headers).toContain("Cache-Control: public, max-age=300");
      expect(headers.match(/Generated by @agent-native\/core/g)).toHaveLength(
        1,
      );
    } finally {
      rmSync(publishDir, { recursive: true, force: true });
    }
  });
});
